# Generated by Django 5.2.7 on 2025-11-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('genderIdentity', models.CharField(blank=True, max_length=100)),
                ('genderAtBirth', models.CharField(blank=True, max_length=100)),
                ('employmentStatus', models.CharField(blank=True, max_length=100)),
                ('relationshipStatus', models.CharField(blank=True, max_length=100)),
                ('griefStatus', models.CharField(blank=True, max_length=100)),
                ('relocationStatus', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
