# Generated by Django 5.2.7 on 2025-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_employmentstatus_exerciseentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employmentStatus',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_statuses',
            field=models.ManyToManyField(blank=True, to='users.employmentstatus'),
        ),
    ]
