# Generated by Django 5.2.7 on 2025-11-13 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employmentstatus_remove_userprofile_employmentstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='journaled',
            new_name='journaled_status',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
