# Generated by Django 5.2.7 on 2025-11-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employment_statuses',
            field=models.ManyToManyField(to='users.employmentstatus'),
        ),
    ]
