# Generated by Django 5.2.7 on 2025-11-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_employment_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employment_statuses',
        ),
    ]
